const Booklist = Vue.component('book-item', {
 props: ['book', 'authorName' ],
 template: "",
});
books =
[
    {id: 66,  locationId: 3, address: 'Field Elementary',	bookTitle: 'Shade of the Tree', authorName: 'Piers Anthony', dateAdded: '5/28/2021', checkedOut: false,},	
{id: 67, locationId: 3,	address: 'Field Elementary', bookTitle: 'Ritual',	authorName: 'William Hefferman', dateAdded: '5/28/2021', checkedOut: true,},
{id: 68, locationId: 3,	address: 'Field Elementary', bookTitle: "The Day Before Midnight",	authorName: 'Stephen Hunter',	datedAdded: '5/28/2021', checkedOut: false,},	
{id: 69, locationId: 3,	address: 'Field Elementary', bookTitle: "Black and Blue", authorName: 'Anna Quindlen',	dateAdded: '5/28/2021', checkedOut: true,},
{id: 70, locationId: 3,	address: 'Field Elementary', bookTitle: "Ladybird Collected", authorName: 'Meg Heriford', dateAdded: '5/28/2021', checkedOut: true,},
{id: 71, locationId: 3,	address: 'Field Elementary', bookTitle: "Heartbreak & Triumph",	authorName: 'Shawn Michaels',	dateAdded: '5/28/2021', checkedOut: false,},	
{id: 72, locationId: 3,	address: 'Field Elementary', bookTitle: "Virgil Wander", authorName: 'Leif Enger',	dateAdded: '5/28/2021', checkedOut: false,},	
{id: 73, locationId: 3,	address: 'Field Elementary', bookTitle: "Into the Cool", authorName: 'Eric D. Schneider', dateAdded: '5/28/2021', checkedOut: false,},	
{id: 74, locationId: 3,	address: 'Field Elementary', bookTitle: "A Kid's Guide to How to Save the Planet", authorName: 'Billy Goodman',	dateAdded: '5/28/2021', checkedOut: false,},	
{id: 75, locationId: 3,	address: 'Field Elementary', bookTitle: 'The First Part Last', authorName: 'Angela Johnson', dateAdded: '5/28/2021', checkedOut: false,},	
{id: 76, locationId: 3,	address: 'Field Elementary', bookTitle: 'Hawaii',	authorName: 'James A. Michener',	dateAdded: '5/28/2021', checkedOut: false,},	
{id: 77, locationId: 3,	address: 'Field Elementary', bookTitle: 'Better Homes and Gardens New Cook Book', authorName: 'Various', dateAdded: '5/28/2021', checkedOut: false,},	
{id: 78, locationId: 3,	address: 'Field Elementary', bookTitle: 'The Road to Omaha', authorName: 'Robert Ludlum', dateAdded: '5/28/2021', checkedOut: false,},	
{id: 79, locationId: 3,	address: 'Field Elementary', bookTitle: "What My Mother Doesn't Know",	authorName: 'Sonya Sones',	dateAdded: '5/28/2021', checkedOut: false,},	
{id: 80, locationId: 3,	address: 'Field Elementary', bookTitle: 'Living Free', authorName: 'Joy Adamson', dateAdded: '5/28/2021', checkedOut: false,},	
{id: 81, locationId: 3,	address: 'Field Elementary', bookTitle: "Private 'I'",	authorName: 'Imogene Forte', dateAdded: '5/28/2021', checkedOut: false,},	
{id: 82, locationId: 3,	address: 'Field Elementary', bookTitle: "New York Minute",	authorName: 'Mary Kate Olsen & Ashley Olsen',	dateAdded: '5/28/2021', checkedOut: false,},	
{id: 83, locationId: 3,	address: 'Field Elementary', bookTitle: "The Two Towers", authorName: "J.R.R. Tolkien",	dateAdded: '5/28/2021', checkedOut: false,},	
{id: 84, locationId: 3,	address: 'Field Elementary', bookTitle: 'The Fellowship of the Ring', authorName: 'J.R.R. Tolkien',	dateAdded: '5/28/2021', checkedOut: false,},	
{id: 85, locationId: 3,	address: 'Field Elementary', bookTitle: 'Knowing the Score', authorName: 'David Morgan',	dateAdded: '5/28/2021', checkedOut: false,},	
{id: 86, locationId: 3,	address: 'Field Elementary', bookTitle: "Rockin' In Time",	authorName: 'David P. Szatmary',	dateAdded: '5/28/2021', checkedOut: false,},	
{id: 87, locationId: 3,	address: 'Field Elementary', bookTitle: 'A Burst of Firsts', authorName: 'J. Patrick Lewis', dateAdded: '5/28/2021', checkedOut: false,},	
{id: 88, locationId: 3,	address: 'Field Elementary', bookTitle: 'Our Gracie Aunt',	authorName: 'Jacqueline Woodson',	dateAdded: '5/28/2021', checkedOut: false,},	
{id: 89, locationId: 3,	address: 'Field Elementary', bookTitle: 'Harald and The Great Stag',	authorName: 'Donald Carrick',	dateAdded: '5/28/2021', checkedOut: false,},	
{id: 90, locationId: 3,	address: 'Field Elementary', bookTitle: 'Think Cool Thoughts',	authorName: 'Elizabeth Goodwin Perry',	dateAdded: '5/28/2021', checkedOut: false,},	
{id: 91, locationId: 3,	address: 'Field Elementary', bookTitle: 'The Really Horrible Horned Toad',	authorName: 'Theresa Greenway',	dateAdded: '5/28/2021', checkedOut: false,},	
{id: 92, locationId: 3,	address: 'Field Elementary', bookTitle: 'Sparrow Hawk Red', authorName: 'Ben Mikaelsen', dateAdded: '5/28/2021', checkedOut: false,},	
{id: 93, locationId: 3,	address: 'Field Elementary', bookTitle: 'Your Three-Year Old', authorName: 'Louise Bates Ames',	dateAdded: '5/28/2021', checkedOut: false,},	
{id: 94, locationId: 3,	address: 'Field Elementary', bookTitle: 'John Billington: Friend of Squato', authorName: 'Clyde Robert Bulla',	dateAdded: '5/28/2021', checkedOut: false,},	
{id: 95, locationId: 3,	address: 'Field Elementary', bookTitle: 'Romeo and Juliet',	authorName: 'William Shakespeare',	dateAdded: '5/28/2021', checkedOut: false,},	
{id: 96, locationId: 3,	address: 'Field Elementary', bookTitle: 'Humanism and Capitalism', authorName: 'Bernard Murchland',  dateAdded: '5/28/2021', checkedOut: false,},	
{id: 97, locationId: 3,	address: 'Field Elementary', bookTitle: 'Human Performance Recruiting',	authorName: 'Stacy Rogers',	dateAdded: '5/28/2021', checkedOut: false,},	
{id: 98, locationId: 3,	address: 'Field Elementary', bookTitle: "A Shepherd's Song", authorName: 'Janice Lane Palko', dateAdded: '5/28/2021', checkedOut: false,},	
{id: 99, locationId: 3,	address: 'Field Elementary', bookTitle: "The Natural Beauty & Bath Book", authorName: 'Casey Kellar', dateAdded: '5/28/2021', checkedOut: false,},	
{id: 100, locationId: 3, address: 'Field Elementary', bookTitle: "Last Stop on Market Street", authorName: 'Matt de la Pena', dateAdded: '5/28/2021', checkedOut: false,},	
{id: 101, locationId: 3, address: 'Field Elementary', bookTitle: "This is the Sun Or Is It?", authorName: 'Kathryn Knight',	dateAdded: '5/28/2021', checkedOut: false,},	
{id: 102, locationId: 3, address: 'Field Elementary', bookTitle: "Franklin Has A Sleepover", authorName: 'Paulette Bourgeois', dateAdded: '5/28/2021', checkedOut: true,},
{id: 103, locationId: 3, address: 'Field Elementary', bookTitle: "Franklin Goes to School",	authorName: 'Paulette Bourgeois', dateAdded: '5/28/2021', checkedOut: true,},
{id: 104, locationId: 3, address: 'Field Elementary', bookTitle: 'Franklin Goes to the Hospital', authorName: 'Paulette Bourgeois', dateAdded: '5/28/2021', checkedOut: true,},
{id: 105, locationId: 3, address: 'Field Elementary', bookTitle: "Nature's Children Ants & Weasels", authorName: 'Caroline Greenland', dateAdded: '5/28/2021', checkedOut: false,},	
{id: 106, locationId: 3, address: 'Field Elementary', bookTitle: 'The Incredibles',	authorName: 'John Sazakalis',	dateAdded: '5/28/2021', checkedOut: false,},	
{id: 107, locationId: 3, address: 'Field Elementary', bookTitle: "Groundhog's Day at the Doctor", authorName: "Judy Denton",	dateAdded: '5/28/2021', checkedOut: false,},	
{id: 108, locationId: 3, address: 'Field Elementary', bookTitle: 'The Last Rail', authorName: 'Darice Bailer', dateAdded: '5/28/2021', checkedOut: false,},	
{id: 109, locationId: 3, address: 'Field Elementary', bookTitle: 'Delivering Justice', authorName: 'James Haskins',	dateAdded: '5/28/2021', checkedOut: false,},	
]